In [6]:
import pandas as pd
import numpy as np

credit_data = "data/credits.csv"
title_data = "data/titles.csv"

credit_df = pd.read_csv(credit_data)
title_df = pd.read_csv(title_data)

In [9]:
title_df.head()

,id,title,type,description,release_year,age_certification,runtime,genres,production_countries,seasons,imdb_id,imdb_score,imdb_votes,tmdb_popularity,tmdb_score
0,tm89464,Miracle on 34th Street,MOVIE,"Kris Kringle, seemingly the embodiment of Sant...",1947,G,96,"['family', 'comedy', 'drama']",['US'],NaN,tt0039628,7.9,50969.0,23.515,7.388
1,tm61729,The Adventures of Ichabod and Mr. Toad,MOVIE,The Wind in the Willows: Concise version of Ke...,1950,G,68,"['horror', 'fantasy', 'animation', 'family', '...",['US'],NaN,tt0041094,6.9,16502.0,16.194,6.500
2,tm61052,Cinderella,MOVIE,Cinderella has faith her dreams of a better li...,1950,G,74,"['fantasy', 'animation', 'family', 'romance']",['US'],NaN,tt0042332,7.3,164292.0,93.547,7.035
3,tm87946,Dumbo,MOVIE,Dumbo is a baby elephant born with over-sized ...,1941,G,64,"['animation', 'drama', 'family', 'fantasy']",['US'],NaN,tt0033563,7.2,135045.0,54.265,6.999
4,tm74391,Fantasia,MOVIE,Walt Disney's timeless masterpiece is an extra...,1941,G,119,"['animation', 'family', 'fantasy', 'music']",['US'],NaN,tt0032455,7.7,98764.0,43.609,7.382

In [13]:
#only shows
titleTV_df=title_df.loc[title_df['type']=="SHOW"]

titleTV_df.head()

,id,title,type,description,release_year,age_certification,runtime,genres,production_countries,seasons,imdb_id,imdb_score,imdb_votes,tmdb_popularity,tmdb_score
88,ts30718,Schoolhouse Rock!,SHOW,Schoolhouse Rock! is an American interstitial ...,1973,NaN,3,"['animation', 'family']",['US'],7.0,tt0069627,8.2,4108.0,3.125,7.800
90,ts22470,The Muppet Show,SHOW,Go behind the curtains as Kermit the Frog and ...,1976,TV-G,25,"['comedy', 'family', 'music']",['GB'],5.0,tt0074028,8.4,25122.0,17.728,8.014
92,ts20949,Zorro,SHOW,"Diego de la Vega, the son of a wealthy landown...",1957,TV-PG,30,"['action', 'drama', 'comedy', 'family', 'weste...",['US'],3.0,tt0050079,8.2,3799.0,59.219,7.720
128,ts24939,Spider-Woman,SHOW,When Jessica Drew was bitten by a poisonous sp...,1979,TV-PG,21,"['animation', 'family', 'fantasy', 'action']",['US'],1.0,tt0197911,5.8,873.0,17.427,7.900
175,ts27944,Spin and Marty,SHOW,Spin and Marty is a popular series of televisi...,1955,NaN,12,"['western', 'family']",['US'],1.0,tt0047775,8.1,323.0,2.725,6.000

In [14]:
#remove NAN
#Clean data

titleTV_df.dropna()

,id,title,type,description,release_year,age_certification,runtime,genres,production_countries,seasons,imdb_id,imdb_score,imdb_votes,tmdb_popularity,tmdb_score
90,ts22470,The Muppet Show,SHOW,Go behind the curtains as Kermit the Frog and ...,1976,TV-G,25,"['comedy', 'family', 'music']",['GB'],5.0,tt0074028,8.4,25122.0,17.728,8.014
92,ts20949,Zorro,SHOW,"Diego de la Vega, the son of a wealthy landown...",1957,TV-PG,30,"['action', 'drama', 'comedy', 'family', 'weste...",['US'],3.0,tt0050079,8.2,3799.0,59.219,7.720
128,ts24939,Spider-Woman,SHOW,When Jessica Drew was bitten by a poisonous sp...,1979,TV-PG,21,"['animation', 'family', 'fantasy', 'action']",['US'],1.0,tt0197911,5.8,873.0,17.427,7.900
203,ts20711,The Simpsons,SHOW,The satiric adventures of a working-class fami...,1989,TV-MA,27,"['animation', 'comedy']",['US'],36.0,tt0096697,8.7,413320.0,538.281,7.989
209,ts15377,America's Funniest Home Videos,SHOW,America's Funniest Home Videos is the longest-...,1989,TV-PG,50,"['comedy', 'reality', 'family']",['US'],34.0,tt0098740,6.2,5545.0,48.068,6.594
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1801,ts296175,Shark Attack Files,SHOW,Scientific experts research about the bizarre ...,2021,TV-14,42,['documentation'],['US'],2.0,tt14811706,6.1,27.0,1.741,10.000
1831,ts219020,Marvel's Moon Girl and Devil Dinosaur,SHOW,After 13-year-old super-genius Lunella acciden...,2023,TV-Y7,24,"['scifi', 'animation', 'action', 'comedy', 'fa...",['US'],1.0,tt8041658,7.6,544.0,31.522,5.800
1838,ts352713,Chasing Waves,SHOW,An docu-series exploring the unique and wonder...,2023,TV-14,41,['documentation'],['AU'],1.0,tt23744508,7.4,47.0,29.001,6.000
1848,ts350456,Superkitties,SHOW,It tells the story of four fierce and furry su...,2023,TV-Y,23,"['family', 'animation', 'action', 'scifi', 'co...",['US'],2.0,tt19872934,7.3,85.0,3.755,6.000
1849,ts305794,7 Toughest Days,SHOW,Dwayne Fields grew up around violent gangs and...,2023,TV-PG,49,"['reality', 'documentation', 'action']",['US'],1.0,tt15257974,7.8,23.0,3.733,2.000